### PR TITLE
Update LCAS.hlsl

### PR DESCRIPTION
**Pull request by Tzugimaa**
Sorry to bother you sir, I just want to remove unnecessary "/ 2".

### CODE REVIEW

**Comment by Blinue** [comment]
Quite reasonable.

**Comment by bloc97** [comment]
Shouldn't the max value be also changed to 2? Since we are no longer dividing the edge by 2 the threshold can be larger than 1.

**Comment by Tzugimaa** [comment]
No,  default was initially 0.2 and max was 1, but then I changed default to 0.1 but didnt change the max value, now it is changed back to 0.2 the same as first version.

**Comment by bloc97** [comment]
Then shouldn't the threshold be multiplied by 2?

**Comment by Tzugimaa** [comment]
If multiplied by 2 the value above 1 should not make any different because at that point it should only detect  texts anyway sir.

**Pull request merged**
