### PR TITLE
Port VL UL upscale variant of Anime4k

### PR DESCRIPTION
**Pull request by kato-megumi**

### CODE REVIEW

**Comment by Blinue** [comment]
Thank you, very nice work. I will take some time to review it.

**Comment by Blinue** [comment]
Amazing work, no one could have done it better. I can imagine how much time was spent on this PR. Many thanks!

**Comment by Blinue** [comment]
@all-contributors please add @kato-megumi for code

**Comment by ayi9752** [comment]
Bro could you please do a port for [Anime4K_Restore_CNN_UL.glsl]. please bro i can pay you like 20 dollar for this.

**Comment by ayi9752** [comment]
@kato-megumi

**Pull request merged**
