### PR TITLE
Update LCAS.hlsl

### PR DESCRIPTION
**Pull request by Tzugimaa**
Added masking and reduced sharpness so it would not over sharpen by default.

Sorry to bother you again sir.

### CODE REVIEW

**Comment by Blinue** [comment]
I'll merge this before v0.9 is released, feel free to modify it until then.

**Comment by Tzugimaa** [comment]
Ok sir.

**Comment by Tzugimaa** [comment]
From my test it has roughly the same speed as built-in FSR now.

Tested in Cyberpunk 2077.

B-FSR

Built-in FSR (Quality)

LCAS

LCAS (900p to 1440p)

CPU : AMD Ryzen 5800H
GPU : Nvidia RTX 3060 6GB - MaxQ
RAM : 32GB

**Comment by Blinue** [comment]
I'm going to release v0.9 soon, is this PR ready to be merged?

**Comment by Blinue** [comment]
Nice work! Thank you.

**Pull request merged**
