### PR TITLE
WIP: localisation & en translation

### PR DESCRIPTION
**Pull request by neoKushan**
Hi, 

Thank you for this wonderful application. I noticed you were looking for help adding localisation support. Moving to WPF definitely helps there.

I have made a start with this work but before I carry on I wanted to put up a WIP (Work-In-Progress / Unfinished) version for you to ensure I am approaching it in a way that you deem acceptable.

I have added some English translations to begin with  -  the main window is mostly translated and some of the options tabs. It will simply pick the localisation of your system. I have ensured that your native language is the "Primary" language, so that if you add a new text or feature you do not need to worry about finding a translation for it. I am sure a volunteer would be happy to offer help updating the .resx files in that case.

You can test localisation by adding `Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");` to the `Application_Startup` Method.

If you are happy with the progress so far, I will continue the translation work to the rest of the application.

Note: I am not a translator, just a developer, so while I cannot guarantee that the translations themselves are correct, I can at least help with the grunt work of getting the translated strings in place.

Screenshot of the work so far:
image

### CODE REVIEW

**Comment by Blinue** [comment]
Hello, thanks for the nice work!

Here is my idea: 

A multilingual application will set the default language to English, because this is the most spoken language, so just do it. In addition, the string identifier can also be set to English, which makes it easier for people to contribute translations.

Just continue your work and if you think you are ready, I will merge it.

**Comment by Blinue** [comment]
If the culture info of OS is not supported by Magpie, it'll fallback to English, I mean.

**Comment by neoKushan** [comment]
That makes complete sense, yes! Thank you for the feedback. I can flip that around easily so English is the default. I will continue work on it and try to get something back for you in a few hours if I can :)

**Comment by neoKushan** [comment]
Hi @Blinue , I have completed the translation work on my end 😇

I have made English the default language and moved all CN strings to a zh-CN resource file. Let me know if that is incorrect or not.

image

I have made sure that the string keys are using the CN text as you are the primary author so this is better for you, but it's easy enough to change them to English keys if you prefer.

I believe I have localised all strings, but I may have missed one or two.

If you or someone else would like to add additional languages, all you need to do is add a new Resources.<lang>.resx file using the correct language code and supply the translations as strings. If the string isn't present, the default english string should be used instead.

I did not implement the language select drop down in the options menu but I feel that would be a good task for another contributor.

**Comment by neoKushan** [comment]
Apologies, I misread your message on the string keys! I shall update the PR now.

**Comment by neoKushan** [comment]
Hi again @Blinue , it is now as you wished for - English text as the string identifier. I hopefully have not made any spelling mistakes!

**Comment by neoKushan** [comment]
I've rebased my branch for easier merging for you as well. Let me know if there's anything else you'd like.

**Comment by Blinue** [comment]
Nice work, thank you.

There's a minor issue. BuiltInScaleModels.zh-CN.json is saved as binary format in resx, which will make the program fail when reading it. I'll merge and tweak it a bit, thanks again!

**Comment by neoKushan** [comment]
Ack, sorry I missed that! But I'm glad it helped, thanks again for the application!

**Pull request merged**
