### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Magpie/UI](https://hosted.weblate.org/projects/magpie/ui/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by Blinue** [comment]
@AndrusGerman Thank you for your contribution, I will merge it when you finish it.

**Comment by AndrusGerman** [comment]
@Blinue I'm done, I'm amazed at what this bot does. I would love to continue contributing to the translation in my free time.
I am open to suggestions and I verify that everything is understood in the application

Thank you for this amazing project to make my small contribution <3

**Comment by Blinue** [comment]
@all-contributors

Please add @AndrusGerman for translation.

**Comment by Blinue** [comment]
@all-contributors

Please add @AndrusGerman for translation.

**Comment by Blinue** [comment]
Please check the latest build in [Actions](https://github.com/Blinue/Magpie/actions).

**Comment by AndrusGerman** [comment]
@Blinue  Everything is incredible, I made some small corrections and I think it's perfect

**Pull request merged**
